# Team Name: **Kubernetes**, Team ID: **336**

In [3]:
import os
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from IPython.core.interactiveshell import InteractiveShell
from glob import glob

InteractiveShell.ast_node_interactivity = 'all'

files = glob('*_submit.csv')
files.sort()

tmps = [
    pd.read_csv('./submissions/013_submit.csv', index_col='id'),
    pd.read_csv('./submissions/010_submit.csv', index_col='id'),
    pd.read_csv('./submissions/009_submit.csv', index_col='id'),
    pd.read_csv('./submissions/007_submit.csv', index_col='id')
]

df = pd.concat(tmps, axis=0)
df = df.reset_index()
df = df.groupby('id').mean()
df

,class0,class1,class2,class3,class4,class5,class6,class7,class8,class9,class10,class11,class12
id,,,,,,,,,,,,,
100001,0.001492,0.001402,0.588861,0.248628,0.148157,7.957516e-07,0.000405,0.000171,0.000205,0.000324,0.009528,0.000106,0.000723
100002,0.002906,0.001363,0.163227,0.019030,0.708678,3.279508e-06,0.000754,0.000404,0.001165,0.000573,0.093605,0.000203,0.008090
100003,0.002787,0.011593,0.518657,0.133644,0.102288,2.142113e-04,0.007004,0.026949,0.005557,0.016538,0.163988,0.001319,0.009461
100004,0.009680,0.003103,0.079392,0.715077,0.016112,2.823547e-07,0.003214,0.000197,0.007681,0.001223,0.022671,0.000176,0.141473
100005,0.006392,0.005502,0.106117,0.036562,0.059508,8.916845e-05,0.008231,0.003335,0.025407,0.005539,0.363124,0.001501,0.378692
...,...,...,...,...,...,...,...,...,...,...,...,...,...
153236,0.003979,0.001236,0.037721,0.815686,0.014128,7.875620e-07,0.004812,0.000484,0.017364,0.001559,0.011482,0.000134,0.091414
153237,0.004575,0.143319,0.147759,0.078265,0.427755,8.104336e-05,0.013650,0.005013,0.022557,0.012627,0.108944,0.009332,0.026124
153238,0.001472,0.006589,0.057253,0.157879,0.729414,2.469328e-06,0.002058,0.001557,0.007054,0.004577,0.024082,0.000755,0.007309
153239,0.010091,0.022804,0.178462,0.373854,0.215568,9.655879e-06,0.011815,0.005888,0.023111,0.016041,0.100610,0.003166,0.038579
153240,0.001176,0.137137,0.319067,0.043260,0.351487,7.001103e-05,0.010514,0.014922,0.037917,0.011583,0.064489,0.005847,0.002530

In [4]:
y_submit = pd.read_csv('data/004_test.csv', index_col='id')

In [5]:
y_submit = y_submit.join(df)
y_submit

,class0,class1,class2,class3,class4,class5,class6,class7,class8,class9,class10,class11,class12
id,,,,,,,,,,,,,
151807,0.004687,0.006146,0.209161,0.028322,0.065225,6.624723e-05,0.004826,0.007569,0.006113,0.004162,0.623719,0.001416,0.038589
118131,0.001209,0.011702,0.710390,0.139657,0.066024,1.401692e-05,0.005162,0.011442,0.004171,0.008839,0.038272,0.000870,0.002248
110921,0.003285,0.026280,0.114774,0.741698,0.010133,2.027017e-05,0.011098,0.005936,0.024963,0.008524,0.039633,0.000543,0.013113
105149,0.002495,0.089779,0.210418,0.296991,0.228552,1.345366e-05,0.009381,0.049841,0.013521,0.014947,0.067223,0.003936,0.012903
143868,0.003549,0.001537,0.021116,0.006355,0.015858,7.106569e-06,0.000951,0.000693,0.001150,0.000766,0.941514,0.000389,0.006115
...,...,...,...,...,...,...,...,...,...,...,...,...,...
146316,0.003371,0.013538,0.081080,0.662899,0.151865,1.979775e-06,0.003917,0.007480,0.009741,0.011660,0.022521,0.000866,0.031060
121816,0.002204,0.001412,0.128508,0.026309,0.339618,1.282079e-05,0.000541,0.000235,0.000540,0.000515,0.496289,0.000380,0.003435
106217,0.000514,0.021279,0.023420,0.100774,0.802497,2.490396e-06,0.003085,0.004186,0.006732,0.003090,0.030381,0.001498,0.002541
103515,0.014520,0.009334,0.106974,0.085045,0.245304,7.311831e-06,0.004975,0.000594,0.015312,0.007389,0.082463,0.001347,0.426736
113723,0.001609,0.000125,0.030592,0.024441,0.007307,7.054037e-07,0.000602,0.000127,0.000333,0.000150,0.930895,0.000047,0.003770

In [6]:
y_submit.to_csv('014_submit.csv')